spring.application.name=springjdbc

spring.datasource.url=jdbc:postgresql://localhost:5432/l1?TimeZone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'
spring.sql.init.mode=always