spring.application.name=demo
spring.security.user.name=Raghav
spring.security.user.password=raghav1234
server.servlet.session.cookie.same-site=strict

spring.datasource.username=user
spring.datasource.password=user
spring.datasource.url=jdbc:postgresql://localhost:5432/usersdb